spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}

app.environment=${APP_ENVIRONMENT:local}

logging.level.io.github.mrav7.softwareoperationsapi=${APP_LOG_LEVEL:INFO}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-components=always
management.endpoint.health.show-details=never
